# site settings
title: Symeon
subtitle: 
email: simospar@gmail.com
description: my personal technical blog related to itsec
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
github_url: https://github.com/symeonp
linkedin_url: https://uk.linkedin.com/in/symeon-paraschoudis-237285145
twitter_url: https://twitter.com/symeonp

# build settings
markdown: kramdown

sass:
  style: compressed
